language: cpp

compiler:
  - gcc
  
before_script:
  - sudo apt-get install libboost-dev
  - autoreconf --install

script:
  - ./configure && make

notifications:
  email: false
  
os:
  - linux
  - osx
