language: cpp

compiler:
  - gcc-4.8

#sudo: false

#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#    - gcc-4.8
#    - g++-4.8
#    - libboost-dev
before_install:
  # g++4.8.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8 cmake
  # We want to compile with g++ 4.8 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  
before_script:
  - sudo apt-get install libboost-dev
  - autoreconf --install

script:
  - cmake .
  - make
  - ./net/Test_InetAddress

notifications:
  email: false
  
os:
  - linux
  # - osx
